pipeline{
  agent any
  stages{
    stage('build'){
      steps{
        sh '''
            echo "Listing WORKSPACE contents:"
            ls -l ${WORKSPACE}
            echo "Build stage is completed"
          '''
      }
    }

    stage('deploy'){
      steps{ 
        sh '''
            echo "Executing the scrip.sh.........."
            bash ${WORKSPACE}/linux/script.sh
            echo "Deployment is successfull"
          '''
      }
    }
  }
}
